version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./conf_dir:/app/conf_dir
      - ./logs:/app/logs
      - ./leaks.txt:/app/leaks.txt
    restart: unless-stopped